services:
  - type: web
    name: car-archiver
    runtime: java
    env: java
    buildCommand: "./mvnw package"
    startCommand: "java -jar target/car-archiver-0.0.1-SNAPSHOT.jar"
    javaVersion: "21" # Or specify the Java version you need
